:GUID: %guid%
:OSP_DOMAIN: %dns_zone%
:GITLAB_URL: %gitlab_url%
:GITLAB_USERNAME: %gitlab_username%
:GITLAB_PASSWORD: %gitlab_password%
:GITLAB_HOST: %gitlab_hostname%
:TOWER_URL: %tower_url%
:TOWER_ADMIN_USER: %tower_admin_user%
:TOWER_ADMIN_PASSWORD: %tower_admin_password%
:SSH_COMMAND: %ssh_command%
:SSH_PASSWORD: %ssh_password%
:VSCODE_UI_URL: %vscode_ui_url%
:VSCODE_UI_PASSWORD: %vscode_ui_password%
:organization_name: Default
:gitlab_project: ansible/gitops-lab
:project_prod: Project gitOps - Prod
:project_test: Project gitOps - Test
:inventory_prod: GitOps inventory - Prod Env
:inventory_test: GitOps inventory - Test Env
:credential_machine: host_credential
:credential_git: gitlab_credential
:credential_git_token: gitlab_token 
:credential_openstack: cloud_credential
:jobtemplate_prod: App deployer - Prod Env
:jobtemplate_test: App deployer - Test Env
:source-linenums-option:        
:markup-in-source: verbatim,attributes,quotes
:show_solution: true
:catalog_name: OpenShift 4 Advanced Infra Deploy ILT
:course_name: Advanced Red Hat OpenShift Container Platform Deployment and Management
:opentlc_portal: link:https://labs.opentlc.com/[OPENTLC lab portal^]
:opentlc_account_management: link:https://www.opentlc.com/account/[OPENTLC Account Management page^]
:opentlc_catalog_name: OPENTLC OpenShift 4 Labs
:opentlc_catalog_item_name_aws: OpenShift 4 Advanced Infra Deploy ILT
:ocp4_docs: link:https://docs.openshift.com/container-platform/4.11/welcome/index.html[OpenShift Container Platform Documentation]

== Overview

In this lab, you will deploy Red Hat OpenShift Container Platform 4 using the User Provided Infrastructure method onto AWS.
These concepts should now be familiar to you, but are also explained with some additional detail here.

OpenShift 4 introduces an entirely new method for deloying and managing OpenShift clusters.
Rather than a complex set of Ansible playbooks that you used in OpenShift 3, Red Hat now provides a single binary that you can use to install an OpenShift 4 cluster in many different environments, such as:

* link:https://docs.openshift.com/container-platform/4.11/installing/installing_alibaba/preparing-to-install-on-alibaba.html[Alibaba^]
* link:https://docs.openshift.com/container-platform/4.11/installing/installing_aws/preparing-to-install-on-aws.html[Amazon Web Services^]
* link:https://docs.openshift.com/container-platform/4.11/installing/installing_azure/preparing-to-install-on-azure.html[Microsoft Azure^]
* link:https://docs.openshift.com/container-platform/4.11/installing/installing_azure_stack_hub/preparing-to-install-on-azure-stack-hub.html[Microsoft Azure Stack Hub^]
* link:https://docs.openshift.com/container-platform/4.11/installing/installing_gcp/preparing-to-install-on-gcp.html[Google Cloud Platform^]
* link:https://docs.openshift.com/container-platform/4.11/installing/installing_openstack/preparing-to-install-on-openstack.html[Red Hat OpenStack^]
* link:https://docs.openshift.com/container-platform/4.11/installing/installing_ibm_cloud_public/preparing-to-install-on-ibm-cloud.html[IBM Cloud VPC^]
* link:https://docs.openshift.com/container-platform/4.11/installing/installing_nutanix/preparing-to-install-on-nutanix.html[Nutanix^]
* link:https://docs.openshift.com/container-platform/4.11/installing/installing_vsphere/preparing-to-install-on-vsphere.html[VMware vSphere^]
* link:https://docs.openshift.com/container-platform/4.11/installing/installing_bare_metal/preparing-to-install-on-bare-metal.html[Bare Metal^]
* link:https://docs.openshift.com/container-platform/4.11/installing/installing_rhv/preparing-to-install-on-rhv.html[Red Hat Virtualization (RHV)^]
* link:https://docs.openshift.com/container-platform/4.11/installing/installing_vmc/preparing-to-install-on-vmc.html[VMC^]

Each of these environments come with their own sets of requirements and allow for different levels of "out of box" automation available for the installer to take advantage of.
For instance, on AWS, Azure, GCP, and Red Hat OpenStack the OpenShift installer can completely automate a deployment of OpenShift 4.11.
This includes provisioning all of the infrastructure and network components as well as deploying the OpenShift software.
Alternately, platforms such as IBM Power and IBM Z Series do not allow for a fully automated solution, but can still be used with manual steps leading up to the actual deployment of OpenShift.
These are the concepts previously discussed as Installer Provided Infrastructure and User Provided Infrastructure.

TIP: You can use the UPI "bare metal" method in many public cloud or IaaS environments not specifically addressed by the installer.

At a high level, Installer Provided Infrasture (IPI) and User Provided Infrastructure (UPI) are very simple in their differences.
The IPI method creates provisions all of the infrastrucure for you from the underlying cloud or IaaS provider.
The UPI method requires you, the cluster administrator, to provision all of the required infrastructure components ahead of time.
More details about infrastructure and other requirements can be found in the appropriate requirements section for the provider, such as link:https://docs.openshift.com/container-platform/4.11/installing/installing_openstack/installing-openstack-installer-custom.html[OpenStack^] or link:https://docs.openshift.com/container-platform/4.11/installing/installing_aws/installing-aws-account.html#installation-aws-limits_installing-aws-account[AWS^].

Some of these infrastructure requirements include:

* Virtual networks (such as Neutron in OpenStack or VPCs in AWS)
* Virtual subnets
* Security Groups
* DNS entries for API, Ingress, etcd, and more
* Virtual Machines or Servers

As easy as OpenShift 4 has made it to deploy and manage OpenShift, there are still challenges that certain customer environments and requirements introduce.
The one that is most often given as a requirement is the need for OpenShift to be installed in a restricted network environment.
