:GUID: %guid%
:OSP_DOMAIN: %dns_zone%
:GITLAB_URL: %gitlab_url%
:GITLAB_USERNAME: %gitlab_username%
:GITLAB_PASSWORD: %gitlab_password%
:GITLAB_HOST: %gitlab_hostname%
:TOWER_URL: %tower_url%
:TOWER_ADMIN_USER: %tower_admin_user%
:TOWER_ADMIN_PASSWORD: %tower_admin_password%
:SSH_COMMAND: %ssh_command%
:SSH_PASSWORD: %ssh_password%
:VSCODE_UI_URL: %vscode_ui_url%
:VSCODE_UI_PASSWORD: %vscode_ui_password%
:organization_name: Default
:gitlab_project: ansible/gitops-lab
:project_prod: Project gitOps - Prod
:project_test: Project gitOps - Test
:inventory_prod: GitOps inventory - Prod Env
:inventory_test: GitOps inventory - Test Env
:credential_machine: host_credential
:credential_git: gitlab_credential
:credential_git_token: gitlab_token 
:credential_openstack: cloud_credential
:jobtemplate_prod: App deployer - Prod Env
:jobtemplate_test: App deployer - Test Env
:source-linenums-option:        
:markup-in-source: verbatim,attributes,quotes
:show_solution: true
:catalog_name: OpenShift 4 Advanced Infra Deploy ILT
:course_name: Advanced Red Hat OpenShift Container Platform Deployment and Management
:opentlc_portal: link:https://labs.opentlc.com/[OPENTLC lab portal^]
:opentlc_account_management: link:https://www.opentlc.com/account/[OPENTLC Account Management page^]
:opentlc_catalog_name: OPENTLC OpenShift 4 Labs
:opentlc_catalog_item_name_aws: OpenShift 4 Advanced Infra Deploy ILT
:ocp4_docs: link:https://docs.openshift.com/container-platform/4.11/welcome/index.html[OpenShift Container Platform Documentation]

== Restricted Network

What does this term really mean?
On the surface, it's easy to understand.
There are, however, levels of nuance that are important to understand when talking about these.

A non-restricted or "connected" environment is the easier to understand of the two.
In a connected environment, there is full access to the Internet for all machines, including the machine you run the installer from.
This access may as of OpenShift 4.11 be through a cluster wide proxy, which can be defined at installation or in a post-installation configuration.
In a connected environment, OpenShift call pull container images, source code, packages, or any other artifacts necessary to install and operate the platform as well as run workloads.
The connected OpenShift cluster also has the ability to send telemetry back to Red Hat for both insights and subscription management.

A restricted network environment is more complex.
When you refer to a restricted network environment, what do you mean?
What components can potentially be disconnected or offline?

[cols="1,2",caption=""]
|====
^a|*Component*
^a|*Considerations*

^.^a|Installation
a|* All images necessary for OpenShift to be installed must be mirrored locally
* OpenShift installer points to `imageContentSource` location for these images during installation

^.^a|Operator Hub
a|* You must pull all operator container images and other Operator Hub components locally
* Current process (as of 4.11) allows you to mirror with a command, similar to what you do for the installation content.
However, not all Operators are currently designed to be easily available in restricted networks

^.^a|Telemetry
a|* You cannot take advantage of any proactive insight from Red Hat
* Turning this off prevents your cluster from reporting back to Red Hat to notify of problems, preventing the Red Hat CCX team to proactively notify support teams

^.^a|Machine Management
a|* Your cluster can no longer provision and deprovision its own machines
* If you are deploying in a private cloud, consider keeping this connected for easier capacity management in the cluster

^.^a|Builds
a|* You must host all of your code and dependencies internally
* Anything that must be pulled from an external sources will not be available

^.^a|Deployments
a|* All of the container images you need to deploy for workloads must be available internally
* Any images that must be pulled from external sources will not be available

^.^a|Authorization
a|* You cannot integrate with an external authentication provider such as an organization SSO
|====

Deciding on a restricted network environment is not an all or nothing approach.
You could install a cluster using a restricted network method and have the resulting cluster be fully connected.
You could also configure that resulting cluster so it is able to connect to the IaaS provider for machine management, but cannot connect to the Internet at large to download content.
Every decision has its trade-offs, some of which are described above and below.

[cols="1,1",caption=""]
|====
^a|*Connected*
^a|*Restricted*

|A fully connected deployment requires Internet access and will pull all necessary content to build and operate the platform
|A restricted network deployment is more flexible and you can choose which components will require Internet access and which ones will pull from and internal source

|IPI or UPI
|UPI

|Easier, but opinionated
|More difficult, but more flexible

|Deploy to supported IaaS provider with full (or proxy) Internet access
|Deploy to any platform, including bare metal
|====

Finally, keep in mind that OpenShift 4 is an "Operator driven platform".
Everything that you need to install the platform is delivered and controlled as an Operator via its container image.
That means no more RPMs or other package dependencies.
