:GUID: %guid%
:OSP_DOMAIN: %dns_zone%
:GITLAB_URL: %gitlab_url%
:GITLAB_USERNAME: %gitlab_username%
:GITLAB_PASSWORD: %gitlab_password%
:GITLAB_HOST: %gitlab_hostname%
:TOWER_URL: %tower_url%
:TOWER_ADMIN_USER: %tower_admin_user%
:TOWER_ADMIN_PASSWORD: %tower_admin_password%
:SSH_COMMAND: %ssh_command%
:SSH_PASSWORD: %ssh_password%
:VSCODE_UI_URL: %vscode_ui_url%
:VSCODE_UI_PASSWORD: %vscode_ui_password%
:organization_name: Default
:gitlab_project: ansible/gitops-lab
:project_prod: Project gitOps - Prod
:project_test: Project gitOps - Test
:inventory_prod: GitOps inventory - Prod Env
:inventory_test: GitOps inventory - Test Env
:credential_machine: host_credential
:credential_git: gitlab_credential
:credential_git_token: gitlab_token 
:credential_openstack: cloud_credential
:jobtemplate_prod: App deployer - Prod Env
:jobtemplate_test: App deployer - Test Env
:source-linenums-option:        
:markup-in-source: verbatim,attributes,quotes
:show_solution: true
:catalog_name: OpenShift 4 Advanced Infra Deploy ILT
:course_name: Advanced Red Hat OpenShift Container Platform Deployment and Management
:opentlc_portal: link:https://labs.opentlc.com/[OPENTLC lab portal^]
:opentlc_account_management: link:https://www.opentlc.com/account/[OPENTLC Account Management page^]
:opentlc_catalog_name: OPENTLC OpenShift 4 Labs
:opentlc_catalog_item_name_aws: OpenShift 4 Advanced Infra Deploy ILT
:ocp4_docs: link:https://docs.openshift.com/container-platform/4.11/welcome/index.html[OpenShift Container Platform Documentation]

== Environment Overview

In this lab, you will be deploying OpenShift 4 into an AWS environment.
While you can do this as a full IPI install, this lab will challenge you to the deployment using the UPI method _and_ in a restricted network mode for the installation.
This means you will have to set up a container image registry and mirror all of the content necessary to complete the installation in addition to the normal steps required to complete a UPI installation.

The lab environment you have ordered consists of several components that are being provided to get you started.
In a real customer engagement, you'd likely have to start from nothing, so the details below are provided both for your future reference and to give you the necessary information to complete this lab.
As always, refer to the link:https://docs.openshift.com/container-platform/4.11/welcome/index.html[OpenShift Documentation^] for up-to-date information on requirements or steps required for a deployment on a specific provider.

////
TBD
[cols="1,1",captions=""]
|====
^a|*Component*
^a|*Details*

^.^a|Project
a|* Name: $GUID-project
* Access:
** Member
* Quotas

^.^a|Network
a|* Name: $GUID-ocp-network
* Includes router for network accessibility

^.^a|Subnet
a|* Name: $GUID-ocp-subnet
* CIDR: 192.168.47.0/24
** Your internal private IPs will come from this subnet

^.^a|API VIP
a|* Name: API VIP on the OCP Subnet
* CIDR: 192.168.47.5
** Your internal private IP dedicated to the API servers

^.^a|Ingress VIP
a|* Name: Ingress VIP on OCP Subnet
* CIDR: 192.168.47.7
** Your internal private IP dedicated to the Ingress servers

^.^a|Security Groups
a|* Master
** Name: $GUID-master_sg
* Worker
** Name: $GUID-worker_sg

^.^a|Virtual Machines
a|* Bastion
** Name: `bastion.$GUID.example.opentlc.com`
** SSH open from Internet
* Utility VM
** Name: `utilityvm.$GUID.internal`
** Only accessible from within environment, including bastion
|====
////

What you build in this lab will be used for the rest of the course.
This is the foundation and needs to be well thought out and stable.
There will be many things that you have to decide on and configure in this lab, so take the time to read, think, understand, and act on everything you do.

=== Before You Start

Read the following and remember as you proceed though the lab content:

* As this lab progresses, you will sometimes be given commands and tasks to perform.
Other times, you will be given requirements and will need to use documentation to figure out how to accomplish the task for that section.
It is meant to be challenging, but everything is able to be completed using your combined knowledge from pre-reqs, module lecture, and documentation.

* Sample outputs that are provided alongside commands in this lab are just that - samples.
Do not take the outputs literally.
Your environments will all have different values and outputs.

* Watch for *substitution*.
For example, if you see `$GUID`, you should be using your assigned GUID.
Fortunately, this is stored as an environment variable for you on your `bastion`.
