:GUID: %guid%
:OSP_DOMAIN: %dns_zone%
:GITLAB_URL: %gitlab_url%
:GITLAB_USERNAME: %gitlab_username%
:GITLAB_PASSWORD: %gitlab_password%
:GITLAB_HOST: %gitlab_hostname%
:TOWER_URL: %tower_url%
:TOWER_ADMIN_USER: %tower_admin_user%
:TOWER_ADMIN_PASSWORD: %tower_admin_password%
:SSH_COMMAND: %ssh_command%
:SSH_PASSWORD: %ssh_password%
:VSCODE_UI_URL: %vscode_ui_url%
:VSCODE_UI_PASSWORD: %vscode_ui_password%
:organization_name: Default
:gitlab_project: ansible/gitops-lab
:project_prod: Project gitOps - Prod
:project_test: Project gitOps - Test
:inventory_prod: GitOps inventory - Prod Env
:inventory_test: GitOps inventory - Test Env
:credential_machine: host_credential
:credential_git: gitlab_credential
:credential_git_token: gitlab_token 
:credential_openstack: cloud_credential
:jobtemplate_prod: App deployer - Prod Env
:jobtemplate_test: App deployer - Test Env
:source-linenums-option:        
:markup-in-source: verbatim,attributes,quotes
:show_solution: true
:catalog_name: OpenShift 4 Advanced Infra Deploy ILT
:course_name: Red Hat OpenStack 17
:opentlc_portal: link:https://labs.opentlc.com/[OPENTLC lab portal^]
:opentlc_account_management: link:https://www.opentlc.com/account/[OPENTLC Account Management page^]
:opentlc_catalog_name: OPENTLC OpenShift 4 Labs
:opentlc_catalog_item_name_aws: OpenShift 4 Advanced Infra Deploy ILT
:ocp4_docs: link:https://docs.openshift.com/container-platform/4.11/welcome/index.html[OpenShift Container Platform Documentation]

== Obtain Overcloud Images

In this lab, you use prebuilt overcloud images. In this section, you obtain the overcloud images.

Red Hat^(R)^ OpenStack^(R)^ Platform director requires several disk images for provisioning overcloud nodes:

[cols="2,3",caption="",options="header"]
|===
|Required Overcloud Image | Usage
|Introspection kernel | Bare-metal system introspection over PXE boot
|Introspection ramdisk | Bare-metal system introspection over PXE boot
|Overcloud kernel | Base overcloud system written to node’s hard disk
|Overcloud ramdisk | Base overcloud system written to node’s hard disk
|Overcloud full image | Base overcloud system written to node’s hard disk
|===

These images are available from the `rhosp-director-images` and `rhosp-director-images-ipa` packages.

NOTE: For custom use cases, overcloud images can be built using `diskimage-builder` or other tools.

. As the `stack` user on `undercloud`, create directories for the overcloud images, templates, and environment files:
+
[source,sh]
----
(undercloud) [stack@undercloud ~]$ mkdir images
(undercloud) [stack@undercloud ~]$ mkdir -p templates/environments
----

. Install software packages containing the overcloud and inspection images:
+
[source,sh]
----
(undercloud) [stack@undercloud ~]$ sudo yum -y install rhosp-director-images
----

. Extract the overcloud images to the `images` directory:
+
[source,sh]
----
(undercloud) [stack@undercloud ~]$ tar -C images -xvf /usr/share/rhosp-director-images/overcloud-full-latest.tar
----
+
.Sample Output
[source,texinfo]
----
overcloud-full.qcow2
overcloud-full.initrd
overcloud-full.vmlinuz
overcloud-full-rpm.manifest
overcloud-full-signature.manifest
----

. Extract the images from the `ironic-python-agent.tar` archive to the `images` directory of the `stack` user's home directory:
+
[source,sh]
----
(undercloud) [stack@undercloud ~]$ tar -C images -xvf /usr/share/rhosp-director-images/ironic-python-agent-latest.tar
----
+
.Sample Output
[source,texinfo]
----
ironic-python-agent.initramfs
ironic-python-agent.kernel
----

. Upload the images to the undercloud's image repository:
+
[source,sh]
----
(undercloud) [stack@undercloud ~]$ openstack overcloud image upload --image-path ~/images
----
+
.Sample Output
[source,texinfo,options="nowrap"]
----
Image "file:///var/lib/ironic/images/overcloud-full.vmlinuz" was copied.
+------------------------------------------------------+----------------+----------+
|                         Path                         |      Name      |   Size   |
+------------------------------------------------------+----------------+----------+
| file:///var/lib/ironic/images/overcloud-full.vmlinuz | overcloud-full | 11173488 |
+------------------------------------------------------+----------------+----------+
Image "file:///var/lib/ironic/images/overcloud-full.initrd" was copied.
+-----------------------------------------------------+----------------+----------+
|                         Path                        |      Name      |   Size   |
+-----------------------------------------------------+----------------+----------+
| file:///var/lib/ironic/images/overcloud-full.initrd | overcloud-full | 65063256 |
+-----------------------------------------------------+----------------+----------+
Image "file:///var/lib/ironic/images/overcloud-full.raw" was copied.
+--------------------------------------------------+----------------+------------+
|                       Path                       |      Name      |    Size    |
+--------------------------------------------------+----------------+------------+
| file:///var/lib/ironic/images/overcloud-full.raw | overcloud-full | 3295805440 |
+--------------------------------------------------+----------------+------------+
----

== Verify Upload of Overcloud Images

. List the overcloud images to confirm that all five images uploaded successfully:
+
[source,sh]
----
(undercloud) [stack@undercloud ~]$ ls -l ~/images/
----
+
.Sample Output
[source,texinfo,options="nowrap"]
----
total 3523572
-rw-r--r--. 1 stack stack  414248944 Sep  8 15:01 ironic-python-agent.initramfs
-rwxr-xr-x. 1 stack stack   11173488 Sep  8 15:01 ironic-python-agent.kernel
-rw-r--r--. 1 stack stack   65063256 Sep  8 15:03 overcloud-full.initrd
-rw-r--r--. 1 stack stack 1054277632 Sep  8 15:36 overcloud-full.qcow2
-rw-r--r--. 1 root  root  3295805440 Dec  5 04:45 overcloud-full.raw
-rw-r--r--. 1 stack stack      33386 Sep  8 15:06 overcloud-full-rpm.manifest
-rw-r--r--. 1 stack stack      87788 Sep  8 15:06 overcloud-full-signature.manifest
-rw-r--r--. 1 stack stack   11173488 Sep  8 15:03 overcloud-full.vmlinuz
----

. Examine the content of the `httpboot` directory to view the director's discovery images and inspection image installation script:
+
[source,sh]
----
(undercloud) [stack@undercloud ~]$ ls -al /var/lib/ironic/httpboot/
----
+
.Sample Output
[source,texinfo,options="nowrap"]
----
total 415460
drwxr-sr-x. 2 42422 42422        86 Nov 24 07:05 .
drwxr-sr-x. 6 42422 42422        66 Nov 24 06:29 ..
-rwxr-xr-x. 1 root  42422  11173488 Nov 24 07:05 agent.kernel
-rw-r--r--. 1 root  42422 414248944 Nov 24 07:05 agent.ramdisk
-rw-r--r--. 1 42422 42422       758 Nov 24 06:29 boot.ipxe
-rw-r--r--. 1 42422 42422       365 Nov 24 06:25 inspector.ipxe
----
*  The inspection images are stored outside the undercloud's OpenStack infrastructure because they are used by the target hosts before they are aware of, or capable of requesting, images from the undercloud. These images are distributed to the hosts using either PXE or iPXE depending on your configuration.

. Examine the `inspector.ipxe` file, which contains instructions on how to boot the hosts:
+
[source,sh]
----
(undercloud) [stack@undercloud ~]$ cat /var/lib/ironic/httpboot/inspector.ipxe
----
+
.Sample Output
[source,texinfo,options="nowrap"]
----
#!ipxe

:retry_boot
imgfree
kernel --timeout 60000 http://192.0.2.1:8088/agent.kernel ipa-inspection-callback-url=http://192.0.2.1:5050/v1/continue ipa-inspection-collectors=default,logs systemd.journald.forward_to_console=yes BOOTIF=${mac}  initrd=agent.ramdisk || goto retry_boot
initrd --timeout 60000 http://192.0.2.1:8088/agent.ramdisk || goto retry_boot
boot
----

== Deploy Containerized Overcloud

During the `openstack undercloud install` step, the `undercloud` server is used as the image registry to synchronize the images from the server defined in the `containers-prepare-parameter.yaml` file.

. List the repositories in the local registry at the undercloud node:
+
[source,sh]
----
(undercloud) [stack@undercloud ~]$ curl -s -H "Accept: application/json" http://192.0.2.1:8787/v2/_catalog | python3 -m json.tool
----
+
.Sample Output
[source,texinfo,options="nowrap"]
----
{
    "repositories": [
        "rhosp-rhel9/openstack-ironic-api",
        "rhosp-rhel9/openstack-ironic-conductor",
        "rhosp-rhel9/openstack-neutron-dhcp-agent",
        "rhosp-rhel9/openstack-heat-api",
        "rhosp-rhel9/openstack-heat-all",
        "rhosp-rhel9/openstack-ironic-pxe",
        "rhosp-rhel9/openstack-neutron-server",
        "rhosp-rhel9/openstack-ironic-neutron-agent",
        "rhosp-rhel9/openstack-rsyslog",
        "rhosp-rhel9/openstack-keystone",
        "rhosp-rhel9/openstack-heat-engine",
        "rhosp-rhel9/openstack-cron",
        "rhosp-rhel9/openstack-ironic-inspector",
        "rhosp-rhel9/openstack-haproxy",
        "rhosp-rhel9/openstack-neutron-openvswitch-agent",
        "rhosp-rhel9/openstack-mariadb",
        "rhosp-rhel9/openstack-memcached",
        "rhosp-rhel9/openstack-iscsid",
        "rhosp-rhel9/openstack-rabbitmq",
        "rhosp-rhel9/openstack-neutron-l3-agent",
        "rhosp-rhel9/openstack-qdrouterd"
    ]
}
----

. Review the log file with the entries from the installation:
+
[source,sh,options="nowrap"]
----
(undercloud) [stack@undercloud ~]$ grep Completed /var/log/tripleo-container-image-prepare.log
----
+
.Sample Output
[source,texinfo,options="nowrap"]
----
2022-11-24 06:24:14,557 14706 INFO tripleo_common.image.image_uploader [  ] [classroom.example.com/rhosp-rhel9/openstack-ironic-api:17.0] Completed upload for image
2022-11-24 06:24:14,934 14706 INFO tripleo_common.image.image_uploader [  ] [classroom.example.com/rhosp-rhel9/openstack-heat-all:17.0] Completed upload for image
2022-11-24 06:24:15,427 14706 INFO tripleo_common.image.image_uploader [  ] [classroom.example.com/rhosp-rhel9/openstack-ironic-pxe:17.0] Completed upload for image
2022-11-24 06:24:15,990 14706 INFO tripleo_common.image.image_uploader [  ] [classroom.example.com/rhosp-rhel9/openstack-neutron-server:17.0] Completed upload for image
<<OMITTED>>
----