== Review General Customization Concepts

The undercloud includes a set of TripleO Heat templates that acts as a plan for your overcloud creation. You can customize aspects of the overcloud using environment files, which are YAML-formatted files that override parameters and resources in the core Heat template collection. You can include as many environment files as necessary. However, the order of the environment files is important because the parameters and resources defined in subsequent environment files take precedence. Use the following list as an example of the environment file order:

* The environment file specifying the number of nodes per role and their flavors. It is vital to include this information for overcloud creation.

* The environment file specifying the location of the container images for containerized OpenStack^(R)^ services. This is the file similar to the one you created previously in the _Overcloud and Container Images Lab_.

* Network configuration environment files:

** Start with the network initialization file (`environments/network-isolation.yaml`) from the TripleO Heat template collection if you plan to implement network isolation in your overcloud. The core TripleO Heat template collection contains Jinja2 templates that are used to generate this file dynamically during the deployment. Do not be surprised if this file is not present in the `/usr/share/openstack-tripleo-heat-templates` directory. Just include the file into your deployment plan.
** Follow with a network environment file with the registry of the NIC configuration templates for different roles and any additional network parameters such as VLANs, IPv4, and IPv6 subnets.

* Any extra files that may be necessary in the advanced deployments, such as:

** External load-balancing environment files
** Storage environment files for Red Hat^(R)^ Ceph^(R)^ Storage, NFS, iSCSI, etc.
** Environment files for Red Hat Content Delivery Network or Red Hat Satellite registration
** Other custom environment files

Some of the core Heat templates for the overcloud are in the Jinja2 format. Red Hat OpenStack Platform director renders them to Heat environment files in the YAML format at the beginning of the overcloud deployment, using roles and network parameters. The default values for these parameters are provided in the `roles_data.yaml` and `network_data.yaml` files. You use them as starting points for customization.

You can use this lab environment to experiment with different OpenStack deployment scenarios. The instructions included in this lab cover only one of them with _Open Virtual Networking (OVN) and Distributed Virtual Routing (DVR) with High Availability (HA)_. This is the default scenario on Red Hat OpenStack Platform 16.

[IMPORTANT]
A basic overcloud uses local LVM storage for block storage, which is not a supported configuration. It is recommended that you use an external storage solution, such as _Red Hat Ceph Storage_ for block storage, but the lab environment does not provide these resources.

== Prepare Environment Files for Overcloud Deployment

. Create directories for the environment files and Heat templates:
+
[source,sh]
----
(undercloud) [stack@undercloud ~]$ mkdir -p ~/templates
----

. Prepare a custom environment file specifying the number of nodes per role and their flavors named `/home/stack/templates/nodes.yaml` :
+
[source,texinfo]
----
- name: Controller
  count: 3
  defaults:
    networks:
    - network: storage
      subnet: storage_subnet
    - network: storage_mgmt
      subnet: storage_mgmt_subnet
    - network: internal_api
      subnet: internal_api_subnet
    - network: tenant
      subnet: tenant_subnet
    - network: external
      subnet: external_subnet
 
    network_config:
      template: templates/multiple_nics/multiple_nics_dvr.j2
      default_route_network:
        - external
  instances:
  - hostname: overcloud-controller-0
    name: ctrl01
    networks:
    - network: ctlplane
      vif: true
      fixed_ip: 192.0.2.201
    - network: storage
      fixed_ip: 172.16.1.201
    - network: storage_mgmt
      fixed_ip: 172.16.3.201
    - network: internal_api
      fixed_ip: 172.16.2.201
    - network: tenant
      fixed_ip: 172.16.0.201
    - network: external
      fixed_ip: 10.0.0.201
     
  - hostname: overcloud-controller-1
    name: ctrl02
    networks:
    - network: ctlplane
      vif: true
      fixed_ip: 192.0.2.202
    - network: storage
      fixed_ip: 172.16.1.202
    - network: storage_mgmt
      fixed_ip: 172.16.3.202
    - network: internal_api
      fixed_ip: 172.16.2.202
    - network: tenant
      fixed_ip: 172.16.0.202
    - network: external
      fixed_ip: 10.0.0.202
  - hostname: overcloud-controller-2
    name: ctrl03
    networks:
    - network: ctlplane
      vif: true
      fixed_ip: 192.0.2.203
    - network: storage
      fixed_ip: 172.16.1.203
    - network: storage_mgmt
      fixed_ip: 172.16.3.203
    - network: tenant
      fixed_ip: 172.16.0.203
    - network: internal_api
      fixed_ip: 172.16.2.203
    - network: external
      fixed_ip: 10.0.0.203
- name: Compute
  count: 2
  defaults:
    network_config:
      template: templates/multiple_nics/multiple_nics_dvr.j2
      default_route_network:
        - external
  instances:
  - hostname: overcloud-novacompute-0
    name: compute01
    networks:
    - network: ctlplane
      vif: true
      fixed_ip: 192.0.2.211
    - network: storage
      fixed_ip: 172.16.1.211
    - network: storage_mgmt
      fixed_ip: 172.16.3.211
    - network: internal_api
      fixed_ip: 172.16.2.211
    - network: tenant
      fixed_ip: 172.16.0.211
    - network: external
      fixed_ip: 10.0.0.211
  - hostname: overcloud-novacompute-1
    name: compute02
    networks:
    - network: ctlplane
      vif: true
      fixed_ip: 192.0.2.212
    - network: storage
      fixed_ip: 172.16.1.212
    - network: storage_mgmt
      fixed_ip: 172.16.3.212
    - network: internal_api
      fixed_ip: 172.16.2.212
    - network: tenant
      fixed_ip: 172.16.0.212
    - network: external
      fixed_ip: 10.0.0.212
----


== Create Custom Network Environment File

Red Hat OpenStack Platform 17 director provides a tool to generate environment files and sample NIC configuration templates using data from `network_data.yaml` files. In this section, you see how to use this tool.

=== Customize Network Data

. For convenience, define the `THT` shell variable as a path to the TripleO Heat templates directory:
+
[source,sh]
----
(undercloud) [stack@undercloud ~]$ THT=/usr/share/openstack-tripleo-heat-templates
----

. Copy the default `network_data.yaml` files from `$THT` to a local directory:
+
[source,sh]
----
(undercloud) [stack@undercloud ~]$ cp $THT/network-data-samples/default-network-isolation.yaml ~/templates/network_data.yaml
----

. Review the `network_data.yaml` file:
+
[source,sh]
----
(undercloud) [stack@undercloud ~]$ egrep -v '^#|^$' templates/network_data.yaml
----
+
.Sample Output
[source,texinfo,options="nowrap"]
----
- name: Storage
  name_lower: storage
  vip: true
  mtu: 1500
  subnets:
    storage_subnet:
      ip_subnet: 172.16.1.0/24
      allocation_pools:
        - start: 172.16.1.4
          end: 172.16.1.250
      vlan: 30
- name: StorageMgmt
  name_lower: storage_mgmt
  vip: true
  mtu: 1500
  subnets:
    storage_mgmt_subnet:
      ip_subnet: 172.16.3.0/24
      allocation_pools:
        - start: 172.16.3.4
          end: 172.16.3.250
      vlan: 40
- name: InternalApi
  name_lower: internal_api
  vip: true
  mtu: 1500
  subnets:
    internal_api_subnet:
      ip_subnet: 172.16.2.0/24
      allocation_pools:
        - start: 172.16.2.4
          end: 172.16.2.250
      vlan: 20
- name: Tenant
  vip: false  # Tenant network does not use VIPs
  mtu: 1500
  name_lower: tenant
  subnets:
    tenant_subnet:
      ip_subnet: 172.16.0.0/24
      allocation_pools:
        - start: 172.16.0.4
          end: 172.16.0.250
      vlan: 50
- name: External
  name_lower: external
  vip: true
  mtu: 1500
  subnets:
    external_subnet:
      ip_subnet: 10.0.0.0/24
      allocation_pools:
        - start: 10.0.0.4
          end: 10.0.0.250
      gateway_ip: 10.0.0.1
      vlan: 10
----

=== Generate Environment Files

In this section, you use a tool to process the core TripleO Heat template collection to produce environment files:

. Copy the TripleO Heat template's  vip-data-default-network-isolation.yaml to home/stack/templates/vip_data.yaml:
+
[source,sh]
----
(undercloud) [stack@undercloud ~]$ cp $THT/network-data-samples/vip-data-default-network-isolation.yaml ~/templates/vip_data.yaml
----

. Copy the TripleO Heat template's roles_data.yaml to home/stack/templates/vip_data.yaml:
+
[source,sh]
----
(undercloud) [stack@undercloud ~]$ cp $THT/roles_data.yaml ~/templates/
----
